routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Página principal
Route::get('/', 'PageController@home')->name('visitor.dashboard.index');

// Autenticación Visitor
Route::auth();

// Obtener municipios
     Route::get('municipios', 'PageController@municipios')->name('municipios');

// Grupo Visitor
Route::group([
     'prefix' => 'visitor',
     'namespace' => 'Visitor',
     'middleware' => 'auth'],
     function(){
          Route::get('/', 'DashboardController@index')->name('visitor.dashboard');
          Route::get('/resource_group/{group_id}', 'ResourceController@index')->name('visitor.resource_group');
          Route::get('/see_resource/{resource_id}', 'ResourceController@see_resource')->name('visitor.see_resource');

          Route::get('my_account', 'UserController@my_account')->name('visitor.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('visitor.my_account_update');
});

// Login Admin
Route::get('/admin/login', 'Auth\LoginAdminController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\LoginAdminController@login');


// Grupo Admin
Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'is_admin'],
      function(){
          Route::get('/', 'DashboardController@index')->name('dashboard');
          Route::resource('visitor', 'UserController', ['as' => 'admin']);
          Route::resource('group', 'ResourceGroupController', ['as' => 'admin']);
          Route::resource('admin', 'AdminController', ['as' => 'admin']);

          Route::post('activate_resource', 'ResourceController@activate_resource')->name('admin.activate_resource');

          Route::get('my_account', 'UserController@my_account')->name('admin.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('admin.my_account_update');


          Route::group(['prefix' => '{group_id}'], function($group_id){
               Route::resource('resource', 'ResourceController');
          });

          Route::post('order_group', 'ResourceGroupController@order_group')->name('admin.order_group');

          Route::post('order_resource', 'ResourceController@order_resource')->name('admin.order_resource');

});

// Salir de sesión
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

app/Http/Controllers/Visitor/DashboardController.php
<?php

namespace App\Http\Controllers\Visitor;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use App\ResourceGroup;


class DashboardController extends Controller
{
    public function index()
    {
         $groups = ResourceGroup::orderBy('order', 'asc')->get();
         return view('visitor.dashboard', compact('groups'));
    }
}

app/Http/Controllers/Visitor/ResourceController.php
<?php

namespace App\Http\Controllers\Visitor;

use App\Resource;
use App\ResourceGroup;
use App\SeenResource;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;


class ResourceController extends Controller
{
     public function index($group_id = false)
     {
          if ($group_id) {
               $group = ResourceGroup::where('id', $group_id)->first();
               $resource = Resource::where('resource_group_id', $group_id)->orderBy('order', 'asc')->get();

               return view('visitor.resources.lista', compact('group', 'resource'));
          }else {
               return response(view('errors.404'), 404);
          }
     }

     public function see_resource($resource_id = false)
     {
          if ($resource_id) {
               $this->register_visit_resource($resource_id);
               $resource = Resource::where('id', $resource_id)->first();
               return view('visitor.resources.resource', compact('resource'));
          }else {
               return response(view('errors.404'), 404);
          }
     }

     public function register_visit_resource($resource_id)
     {
          $user_id =  Auth::user()->id;
          $existe = SeenResource::where('user_id', $user_id)->where('resource_id', $resource_id)->first();

          $data['user_id'] = Auth::user()->id;
          $data['resource_id'] = $resource_id;
          if ($existe) {
               $registe = $existe->update( $data );
          }else{
               $registe = SeenResource::create($data);
          }

          return $registe;
     }
}

app/Http/Controllers/Visitor/UserController.php
<?php

namespace App\Http\Controllers\Visitor;

use App\User;
use App\Specialty;
use App\Resource;
use App\State;
use App\Municipality;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;


class UserController extends Controller
{
     public function my_account()
     {
          $states = State::all();
          $specialties = Specialty::all();
          $municipalitys = array();
          $months = ['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'];

          $user = User::where('id', Auth::user()->id)->first();

          if ($user->state_id) {
               $municipalitys = Municipality::where('estado_id', $user->state_id)->get();
          }

          return view('visitor.my_account', compact('user', 'specialties', 'states', 'municipalitys', 'months'));
     }

     public function my_account_update(Request $request)
     {
          $user = User::where('id', Auth::user()->id)->first();

          $data = $request->validate([
               'name' => 'required|string|max:255',
               'email' => 'required|string|email|max:255|unique:users,email,'.$user->id,
          ]);

          if($request->filled('password')) {
               $data =  $request->validate([
                    'password' => 'confirmed', 'min:7',
               ]);
               $data['password'] = bcrypt(request('password'));
          }

          $data['status'] = request('status') ? request('status') : 0;
          $data['surnames'] = request('surnames') ;
          $data['specialty_id'] = request('specialty_id') ;
          $data['state_id'] = request('state_id');
          $data['municipality_id'] = request('municipality_id');
          $data['birthdate'] = date("Y-m-d", strtotime(request('day').'-'.request('month').'-'.request('year')));
          $data['cedula'] = request('cedula');



          $user->update( $data );

          return redirect()->route('visitor.dashboard')->with('success', 'Informacón actualizada');
     }
}

resources/views/admin/visitors/create.blade.php
@extends('admin.layout')

@section('content')


<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <h4 class="card-title">
                         Nuevo participante
                    </h4>
               </div>
               <div class="card-content ">
                    <form class="form" method="post" action="{{ route('admin.visitor.store') }}">
                         {{ csrf_field() }}
                         <div class="row">
                              <div class="col-md-12">
                                   @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                        <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                                   @endif
                              </div>
                         </div>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" placeholder="Nombre" name="name" class="form-control" value="{{ old('name') }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Apellidos</label>
                                        <input type="text" name="surnames" placeholder="Apellidos" class="form-control" value="{{ old('surnames') }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Especialiedad</label>
                                        <select class="form-control" name="specialty_id">
                                             @foreach($specialties as $key => $specialty)
                                             <option @if( old('specialty_id') == $specialty->id ) checked @endif  value="{{ $specialty->id }}">{{ $specialty->name }}</option>
                                             @endforeach
                                        </select>
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Correo</label>
                                        <input type="email"  value="{{ old('email') }}" name="email" placeholder="Correo" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label for="name" class="control-label">Estado</label>
                                        <select class="form-control" name="state_id" required id="estado_id" onchange="get_municipios()" >
                                             @foreach($states as $key => $state)
                                             <option value="{{ $state->id }}">{{ $state->nombre }}</option>
                                             @endforeach
                                        </select>

                                        @if ($errors->has('state_id'))
                                        <span class="help-block">
                                             <strong>{{ $errors->first('state_id') }}</strong>
                                        </span>
                                        @endif
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label for="municipality_id" class="control-label">Municipio / Ciudad </label>

                                        <select class="form-control" name="municipality_id" id="municipio_id" required>

                                        </select>

                                        @if ($errors->has('municipality_id'))
                                        <span class="help-block">
                                             <strong>{{ $errors->first('municipality_id') }}</strong>
                                        </span>
                                        @endif
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <label for="cedula" >Cédula</label>
                                   <input id="cedula" type="text" class="form-control" name="cedula" value="{{  $user->cedula }}" autofocus>

                                   @if ($errors->has('cedula'))
                                   <span class="help-block">
                                        <strong>{{ $errors->first('cedula') }}</strong>
                                   </span>
                                   @endif

                              </div>
                              <div class="col-md-6">
                                   <label>Fecha de nacimiento</label>
                                   <div class="row">
                                        <div class="col-xs-3">
                                             <select class="form-control" name="day">
                                                  <option hidden value="">Día</option>
                                                  <?php for($j = 0; $j <= 31; $j++){ ?>
                                                       <option
                                                            value="<?=$j?>"
                                                       ><?=$j?></option>
                                                  <?php } ?>
                                             </select>
                                        </div>
                                        <div class="col-xs-6">
                                             <select class="form-control" name="month">
                                                  <option hidden value="">Mes</option>
                                                  <?php foreach ($months as $key => $month){?>
                                                       <option
                                                            value="<?=$key+1?>"
                                                       ><?=$month?></option>
                                                  <?php } ?>
                                             </select>
                                        </div>
                                        <div class="col-xs-3">
                                             <select class="form-control" name="year">
                                                  <option hidden value="">Año</option>
                                                  <?php for($j = 1920; $j <= date("Y"); $j++){ ?>
                                                       <option
                                                            value="<?=$j?>"
                                                       ><?=$j?></option>
                                                  <?php } ?>
                                             </select>
                                        </div>
                                   </div>

                                   @if ($errors->has('birthdate'))
                                   <span class="help-block">
                                        <strong>{{ $errors->first('birthdate') }}</strong>
                                   </span>
                                   @endif
                              </div>
                         </div>
                         <hr>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Contraseña</label>
                                        <input type="password" name="password" placeholder="Contraseña" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Confirmar Contraseña</label>
                                        <input type="password" name="password_confirmation" placeholder="Confirmar contraseña" class="form-control">
                                   </div>
                              </div>
                         </div>
                         <hr>

                         <a  href="{{ url('admin/visitor') }}" class="btn btn-fill btn-wd btn-default">
                              <i class="fa fa-arrow-left" aria-hidden="true"></i>
                              Regresar
                         </a>
                         <button type="submit" class="btn btn-fill btn-success btn-wd pull-right">
                              <i class="fa fa-floppy-o" aria-hidden="true"></i>
                              Registrar participante
                         </button>
                    </form>
               </div>
          </div>
     </div>
</div>
@stop


@push('style')
<link href="https://unpkg.com/gijgo@1.9.13/css/gijgo.min.css" rel="stylesheet" type="text/css" />
@endpush


@push('scripts')
<script src="https://unpkg.com/gijgo@1.9.13/js/gijgo.min.js" type="text/javascript"></script>

<script>
$( document ).ready(function() {
     get_municipios();

     $('.datetimepicker').datepicker({
          format: 'dd-mm-yyyy'
     });
});


function get_municipios(){
     $('#municipio_id').html('');
     $.ajax({
          url: "{{ route('municipios') }}",
          data:{'estado_id': $('#estado_id').val()},
          type:'get',
          success:  function (response) {
               $('#municipio_id').html();
               $.each(response, function (i, item) {
                    $('#municipio_id').append($('<option>', {
                         value: item.id,
                         text : item.nombre
                    }));
               });
               $('#municipio_id').append($('<option>', {
                    value: '3000',
                    text : 'Otro'
               }));
          },
          statusCode: {
               404: function() {
                    alert('web not found');
               }
          },
          error:function(x,xs,xt){
               //alert('error: ' + JSON.stringify(x) +"\n error string: "+ xs + "\n error throwed: " + xt);
          }
     });
}

</script>
@endpush

resources/views/admin/visitors/index.blade.php
@extends('admin.layout')

@section('content')

<div class="row">
     <div class="col-xs-6">
          <a href="{{ url('/admin') }}">
               <h4 style="margin-top:3px;"><span class="label label-success">
                    <i class="fa fa-arrow-left"></i> Atras</span></h4>
          </a>
     </div>
     <div class="col-xs-6" style="text-align: right;">
          <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Inicio</a></li>
               <li class="breadcrumb-item active" aria-current="page">Lista de visitantes</li>
          </ol>
     </div>
</div>

<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <a href="{{ route('admin.visitor.create') }}" class="btn btn-wd btn-success" style="float:right; z-index:9999;">
                         <span class="btn-label">
                              <i class="fa fa-plus"></i>
                         </span>
                         Agregar un nuevo visitante
                    </a>
                    <h4 class="card-title">Lista de visitantes</h4>
                    <p class="category">Visitantes registrados</p>

               </div>
               <div class="card-content table-responsive table-full-width">
                    <table class="table">
                         <thead>
                              <tr>
                                   <th class="text-center">#</th>
                                   <th>Nombre</th>
                                   <th>Especialidad</th>
                                   <th class="text-center">Material consultado</th>
                                   <th class="text-center">Estatus</th>
                                   <th class="text-center">Actions</th>
                              </tr>
                         </thead>
                         <tbody>
                              @forelse($users as $key => $user)
                              <tr>
                                   <td class="text-center">{{ $user->id }}</td>
                                   <td>{{ $user->name }} {{ $user->surnames }}</td>
                                   <td>{{ $user->specialty->name }}</td>
                                   <td class="text-center"> {{ $user->resources_seen->count() }}  de {{ $resource->count() }} </td>
                                   <td class="text-center">
                                        @if($user->status == 1)
                                        <span class="label label-success">Activo</span>
                                        @else
                                        <span class="label label-danger">Inactivo</span>
                                        @endif
                                   </td>
                                   <td class="td-actions text-center">
                                        <a href="{{ route('admin.visitor.edit', $user) }}" rel="tooltip" title="" class="btn btn-success  btn-simple btn-xs" data-original-title="Editar">
                                             <i class="ti-pencil-alt"></i>
                                        </a>
                                        <form method="POST"
                                   action="{{ route('admin.visitor.destroy', $user) }}"
                                   style="display:inline">
                                   {{ csrf_field() }} {{ method_field('DELETE') }}
                                   <button class="btn btn-xs btn-simple btn-danger"
                                        onclick="return confirm('¿ Estás seguro de querer eliminar este participante ?')"
                                    >
                                    <i class="fa fa-trash"></i>
                                   </button>
                              </form>
                              </td>
                         </tr>
                         @empty
                         <tr>
                              <td colspan="5" class="text-center">Sin registros</td>
                         </tr>
                         @endforelse
                    </tbody>
               </table>
          </div>
     </div>
</div>
</div>
@stop