routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Página principal
Route::get('/', 'PageController@home')->name('visitor.dashboard.index');

// Autenticación Visitor
Route::auth();

// Obtener municipios
     Route::get('municipios', 'PageController@municipios')->name('municipios');

// Grupo Visitor
Route::group([
     'prefix' => 'visitor',
     'namespace' => 'Visitor',
     'middleware' => 'auth'],
     function(){
          Route::get('/', 'DashboardController@index')->name('visitor.dashboard');
          Route::get('/resource_group/{group_id}', 'ResourceController@index')->name('visitor.resource_group');
          Route::get('/see_resource/{resource_id}', 'ResourceController@see_resource')->name('visitor.see_resource');

          Route::get('my_account', 'UserController@my_account')->name('visitor.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('visitor.my_account_update');
});

// Login Admin
Route::get('/admin/login', 'Auth\LoginAdminController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\LoginAdminController@login');


// Grupo Admin
Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'is_admin'],
      function(){
          Route::get('/', 'DashboardController@index')->name('dashboard');
          Route::resource('visitor', 'UserController', ['as' => 'admin']);
          Route::resource('group', 'ResourceGroupController', ['as' => 'admin']);
          Route::resource('admin', 'AdminController', ['as' => 'admin']);

          Route::post('activate_resource', 'ResourceController@activate_resource')->name('admin.activate_resource');

          Route::get('my_account', 'UserController@my_account')->name('admin.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('admin.my_account_update');


          Route::group(['prefix' => '{group_id}'], function($group_id){
               Route::resource('resource', 'ResourceController');
          });

          Route::post('order_group', 'ResourceGroupController@order_group')->name('admin.order_group');

          Route::post('order_resource', 'ResourceController@order_resource')->name('admin.order_resource');

});

// Salir de sesión
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/admin/dashboard.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-content">
                    <div class="row">
                         <div class="col-md-5 text-center">
                              <h1>Bienvenid@</h1>
                         </div>
                         <div class="col-md-7 text-center" style="margin-top:30px;">
                              <a href="{{ route('admin.my_account') }}" type="button" class="btn btn-wd btn-info btn-lg">
                                   <span class="btn-label">
                                        <i class="fa fa-user" aria-hidden="true"></i>
                                   </span>
                                   Mi cuenta
                              </a>
                              <a  href="{{ url('/logout') }}" class="btn btn-wd btn-default btn-lg mb-4">
                                   <span class="btn-label">
                                        <i class="ti-power-off"></i>
                                   </span>
                                   Salir
                              </a>
                         </div>
                    </div>
               </div>
               <div class="card-footer">
                    <hr>
                    <div class="row">
                         <div class="col-md-6">
                              <div class="row">

                                   <div class="col-md-10 col-sm-offset-1">
                                        <div class="numbers" style="text-align:left;">
                                             <span style="font-size: 50px;">  <i class="fa fa-users " aria-hidden="true" style="color: #a5bbce"></i> {{ $users->count()}}</span>
                                             <p>VISITANTES REGISTRADOS</p>
                                        </div>
                                   </div>
                              </div>
                              <hr>
                              <div class="row">
                                   <div class="col-md-10 col-sm-offset-1">
                                        <a href="{{ url('admin/visitor') }}" class="btn btn-wd btn-block btn-primary btn-lg">
                                             <span class="btn-label">
                                                  <i class="fa fa-list"></i>
                                             </span>
                                             Ver lista de visitantes
                                        </a>
                                        <br>
                                        <a href="{{ route('admin.visitor.create') }}" class="btn btn-wd btn-block btn-success btn-lg">
                                             <span class="btn-label">
                                                  <i class="fa fa-plus"></i>
                                             </span>
                                             Agregar un visitante
                                        </a>
                                   </div>
                              </div>
                         </div>
                         <div class="col-md-6">
                              <div class="row">

                                   <div class="col-md-10 col-sm-offset-1">
                                        <div class="numbers" style="text-align:left;">

                                             <span style="font-size: 50px;"><i class="fa fa-archive " aria-hidden="true" style="color: #a5bbce"></i>
                                                  {{ $groups->count() }}</span>
                                             <p>GRUPO DE RECURSOS</p>
                                        </div>
                                   </div>
                              </div>
                              <hr>
                              <div class="row">
                                   <div class="col-md-10 col-sm-offset-1">
                                        <div class="grup_recursos">
                                             <ul id="example1" class="list-group">
                                                  @forelse ($groups as $group)

                                                       <li id="{{$group->id}}"  class="list-group-item d-flex justify-content-between align-items-center">
                                                            <a href="{{ url('admin/'.$group->id.'/resource') }}">
                                                                 {{ $group->name }}

                                                            </a>
                                                            <!-- <a href="javascript:void(0)" style="padding: 0px 5px 10px 10px; margin-top: -2px;" id="group-user" data-id="{{ $group->id }}" class="btn btn-danger pull-right btn-simple" >
                                                                 <i class="ti-trash"></i>
                                                            </a> -->
                                                            <form method="POST"
                                                                 action="{{ route('admin.group.destroy', $group) }}"
                                                                 style="display:inline">
                                                                 {{ csrf_field() }} {{ method_field('DELETE') }}
                                                                 <button class="btn btn-xs btn-simple btn-danger"
                                                                      onclick="return confirm('¿ Estás seguro de querer eliminar este grupo ?')"
                                                                 >
                                                                 <i class="fa fa-trash"></i>
                                                                 </button>
                                                            </form>
                                                            <a href="javascript:void(0)" style="padding: 0px 5px 10px 10px; margin-top: 1px;" id="group-user" data-id="{{ $group->id }}" class="btn btn-success pull-right btn-simple" >
                                                                 <i class="ti-pencil-alt"></i>
                                                            </a>

                                                            <span class="badge badge-primary badge-pill">{{ $group->resources->count() }}</span>
                                                       </li>

                                                  @empty
                                                  <p>No hay grupos.</p>
                                                  @endforelse
                                             </ul>
                                        </div>
                                   </div>
                                   <div class="col-md-10 col-sm-offset-1">
                                        <a href="javascript:void(0)" id="create-new-user" class="btn btn-wd btn-block btn-success btn-lg">
                                             <span class="btn-label">
                                                  <i class="fa fa-plus"></i>
                                             </span>
                                             Agregar un grupo
                                        </a>
                                   </div>
                              </div>
                         </div>
                    </div>
                    <hr>
                    <div class="row">
                         <div class="col-md-6">
                              <div class="row">

                                   <div class="col-md-10 col-sm-offset-1">
                                        <div class="numbers" style="text-align:left;">
                                             <span style="font-size: 50px;"><i class="fa fa-lock " aria-hidden="true" style="color: #a5bbce"></i> {{ $admin->count()}}</span>
                                             <p>ADMINISTRADORES REGISTRADOS</p>
                                        </div>
                                        <hr>
                                        <div class="row">
                                             <div class="col-md-10 col-sm-offset-1">
                                                  <a href="{{ url('admin/admin') }}" class="btn btn-wd btn-block btn-primary btn-lg">
                                                       <span class="btn-label">
                                                            <i class="fa fa-list"></i>
                                                       </span>
                                                       Ver lista de administradores
                                                  </a>
                                                  <br>
                                                  <a href="{{ route('admin.admin.create') }}" class="btn btn-wd btn-block btn-success btn-lg">
                                                       <span class="btn-label">
                                                            <i class="fa fa-plus"></i>
                                                       </span>
                                                       Agregar un administrador
                                                  </a>
                                             </div>
                                        </div>
                                   </div>
                              </div>
                         </div>
          </div>
     </div>
</div>
@stop
@include('admin.resourcegroup.ajax_crud_modal')
@push('scripts')
<script src="{!! asset('js/Sortable.js') !!}" charset="utf-8"></script>
<script src="{!! asset('js/st/prettify/prettify.js') !!}" charset="utf-8"></script>
<script src="{!! asset('js/st/prettify/run_prettify.js') !!}" charset="utf-8"></script>
<script>
     var example1 = document.getElementById('example1');
     new Sortable(example1, {
     	animation: 150,
     	ghostClass: 'blue-background-class',
          onUpdate: function(evt) {
          console.log(evt);
          var order= $("#example1 li").map(function() {
               return this.id;
          }).get();
            f='order='+order;
            $.ajax({
                 type: "POST",
                 data : f,
                 cache: false,
                 url: " {{ route('admin.order_group')}}",
                 success: function(data){
                    //success
                 }
            });
	    },
     });

</script>

@endpush

resources/views/admin/layout.blade.php
<!doctype html>
<html lang="en">
<head>
     <meta charset="utf-8" />
     <link rel="apple-touch-icon" sizes="76x76" href="{!! asset('theme/img/apple-icon.png') !!}">
     <link rel="icon" type="image/png" sizes="96x96" href="{!! asset('theme/img/favicon.png') !!}">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
     <meta name="csrf-token" content="{{ csrf_token() }}">
     <title>{{ config('app.name') }}</title>


     <meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
     <meta name="viewport" content="width=device-width" />


     <!-- Bootstrap core CSS     -->
     <link href="{!! asset('theme/css/bootstrap.min.css') !!}" rel="stylesheet" />

     <!--  Paper Dashboard core CSS    -->
     <link href="{!! asset('theme/css/paper-dashboard.css') !!}" rel="stylesheet"/>


     <!--  CSS for Demo Purpose, don't include it in your project     -->
     <link href="{!! asset('theme/css/demo.css') !!}" rel="stylesheet" />


     <!--  Fonts and icons     -->
     <link href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" rel="stylesheet">
     <link href='https://fonts.googleapis.com/css?family=Muli:400,300' rel='stylesheet' type='text/css'>
     <link href="{!! asset('theme/css/themify-icons.css') !!}" rel="stylesheet">

     @stack('style')


     <div class="main-panel">
          <nav class="navbar navbar-default">
               <div class="container-fluid">

                    <div class="navbar-header">
                         <button type="button" class="navbar-toggle">
                              <span class="sr-only">Toggle navigation</span>
                              <span class="icon-bar bar1"></span>
                              <span class="icon-bar bar2"></span>
                              <span class="icon-bar bar3"></span>
                         </button>
                         <a class="navbar-brand" href="/admin">
                              <img src="{{URL::asset('/img/logo.png')}}" alt="SANED" style="width:100px;">
                         </a>
                    </div>
                    <div class="collapse navbar-collapse">

                         <ul class="nav navbar-nav navbar-right">
                              <li>
                                   <a href="{{ url('/admin') }}" class="btn-rotate">
                                        <i class="ti-home"></i>
                                        Inicio
                                   </a>
                              </li>
                              <li>

                                   <a href="{{ url('/logout') }}" class="btn-rotate">
                                        <i class="ti-power-off"></i>
                                        Salir
                                   </a>
                              </li>
                         </ul>
                    </div>
               </div>
          </nav>
          <div class="content">
               <div class="container">
                    <div class="container-fluid">

                         @include('partials.flash-message')

                         @yield('content')
                    </div>
               </div>
          </div>

          <footer class="footer">
               <div class="container-fluid">

                    <div class="copyright pull-right">
                    &copy; <script>document.write(new Date().getFullYear())</script> -   Elaborado por grupo saned
                    </div>
               </div>
          </footer>
     </div>
</div>

</body>

<!--   Core JS Files. Extra: TouchPunch for touch library inside jquery-ui.min.js') !!}   -->
<script src="{!! asset('theme/js/jquery.min.js') !!}" type="text/javascript"></script>
<script src="{!! asset('theme/js/jquery-ui.min.js') !!}" type="text/javascript"></script>
<script src="{!! asset('theme/js/perfect-scrollbar.min.js') !!}" type="text/javascript"></script>
<script src="{!! asset('theme/js/bootstrap.min.js') !!}" type="text/javascript"></script>

<!--  Forms Validations Plugin -->
<script src="{!! asset('theme/js/jquery.validate.min.js') !!}"></script>

<!-- Promise Library for SweetAlert2 working on IE -->
<script src="{!! asset('theme/js/es6-promise-auto.min.js') !!}"></script>

<!--  Plugin for Date Time Picker and Full Calendar Plugin-->
<script src="{!! asset('theme/js/moment.min.js') !!}"></script>

<!--  Date Time Picker Plugin is included in this js file -->
<script src="{!! asset('theme/js/bootstrap-datetimepicker.js') !!}"></script>

<!--  Select Picker Plugin -->
<script src="{!! asset('theme/js/bootstrap-selectpicker.js') !!}"></script>

<!--  Switch and Tags Input Plugins -->
<script src="{!! asset('theme/js/bootstrap-switch-tags.js') !!}"></script>

<!-- Circle Percentage-chart -->
<script src="{!! asset('theme/js/jquery.easypiechart.min.js') !!}"></script>

<!--  Charts Plugin -->
<script src="{!! asset('theme/js/chartist.min.js') !!}"></script>

<!--  Notifications Plugin    -->
<script src="{!! asset('theme/js/bootstrap-notify.js') !!}"></script>

<!-- Sweet Alert 2 plugin -->
<script src="{!! asset('theme/js/sweetalert2.js') !!}"></script>

<!-- Vector Map plugin -->
<script src="{!! asset('theme/js/jquery-jvectormap.js') !!}"></script>

<!-- Wizard Plugin    -->
<script src="{!! asset('theme/js/jquery.bootstrap.wizard.min.js') !!}"></script>

<!--  Bootstrap Table Plugin    -->
<script src="{!! asset('theme/js/bootstrap-table.js') !!}"></script>

<!--  Plugin for DataTables.net  -->
<script src="{!! asset('theme/js/jquery.datatables.js') !!}"></script>

<!--  Full Calendar Plugin    -->
<script src="{!! asset('theme/js/fullcalendar.min.js') !!}"></script>

<!-- Paper Dashboard PRO Core javascript and methods for Demo purpose -->
<script src="{!! asset('theme/js/paper-dashboard.js') !!}"></script>

<!--   Sharrre Library    -->
<script src="{!! asset('theme/js/jquery.sharrre.js') !!}"></script>

<!-- Paper Dashboard PRO DEMO methods, don't include it in your project! -->
<script src="{!! asset('theme/js/demo.js') !!}"></script>

<script>

//Script Eliminar
$(".eliminar").submit(function(e){
     e.preventDefault();

     Swal.fire({
          title: '¿ Desea eliminar ?',
          text: "¡No podrás revertir esto!",
          type: 'warning',
          showCancelButton: true,
          confirmButtonColor: '#3085d6',
          cancelButtonColor: '#d33',
          confirmButtonText: 'Si, eliminar',
          cancelButtonText: 'Cancelar'
     }).then((result) => {
          if (result.value) {
               $(".eliminar").off("submit").submit();
          }else {
               return false;
          }
     })
});
</script>

@stack('scripts')

</html>

resources/views/admin/my_account.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <h4 class="card-title">
                         Editar participante
                    </h4>
               </div>
               <div class="card-content ">
                    <form class="form" method="post" action="{{ route('admin.my_account_update') }}">
                         {{ csrf_field() }} {{ method_field('PUT') }}
                         <div class="row">
                              <div class="col-md-12">
                                   @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                        <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                                   @endif
                              </div>
                         </div>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" placeholder="Nombre" name="name" class="form-control"  value="{{ $user->name }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Apellidos</label>
                                        <input type="text" name="surnames" placeholder="Apellidos" class="form-control" value="{{ $user->surnames }}">
                                   </div>
                              </div>

                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>Correo</label>
                                        <input type="email"  value="{{  $user->email }}" name="email" placeholder="Correo" class="form-control">
                                   </div>
                              </div>
                         </div>
                         <hr>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Contraseña</label>
                                        <input type="password" name="password" placeholder="Contraseña" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Confirmar Contraseña</label>
                                        <input type="password" name="password_confirmation" placeholder="Confirmar contraseña" class="form-control">
                                   </div>
                              </div>
                         </div>
                         <hr>

                         <a  href="{{ url('admin/') }}" class="btn btn-fill btn-wd btn-default">
                              <i class="fa fa-arrow-left" aria-hidden="true"></i>
                              Regresar
                         </a>
                         <button type="submit" class="btn btn-fill btn-success btn-wd pull-right">
                              <i class="fa fa-floppy-o" aria-hidden="true"></i>
                              Registrar participante
                         </button>
                    </form>
               </div>
          </div>
     </div>
</div>
@stop