routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Página principal
Route::get('/', 'PageController@home')->name('visitor.dashboard.index');

// Autenticación Visitor
Route::auth();

// Obtener municipios
     Route::get('municipios', 'PageController@municipios')->name('municipios');

// Grupo Visitor
Route::group([
     'prefix' => 'visitor',
     'namespace' => 'Visitor',
     'middleware' => 'auth'],
     function(){
          Route::get('/', 'DashboardController@index')->name('visitor.dashboard');
          Route::get('/resource_group/{group_id}', 'ResourceController@index')->name('visitor.resource_group');
          Route::get('/see_resource/{resource_id}', 'ResourceController@see_resource')->name('visitor.see_resource');

          Route::get('my_account', 'UserController@my_account')->name('visitor.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('visitor.my_account_update');
});

// Login Admin
Route::get('/admin/login', 'Auth\LoginAdminController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\LoginAdminController@login');


// Grupo Admin
Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'is_admin'],
      function(){
          Route::get('/', 'DashboardController@index')->name('dashboard');
          Route::resource('visitor', 'UserController', ['as' => 'admin']);
          Route::resource('group', 'ResourceGroupController', ['as' => 'admin']);
          Route::resource('admin', 'AdminController', ['as' => 'admin']);

          Route::post('activate_resource', 'ResourceController@activate_resource')->name('admin.activate_resource');

          Route::get('my_account', 'UserController@my_account')->name('admin.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('admin.my_account_update');


          Route::group(['prefix' => '{group_id}'], function($group_id){
               Route::resource('resource', 'ResourceController');
          });

          Route::post('order_group', 'ResourceGroupController@order_group')->name('admin.order_group');

          Route::post('order_resource', 'ResourceController@order_resource')->name('admin.order_resource');

});

// Salir de sesión
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/admin/admin/create.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <h4 class="card-title">
                         Nuevo administrador
                    </h4>
               </div>
               <div class="card-content ">
                    <form class="form" method="post" action="{{ route('admin.admin.store') }}">
                         {{ csrf_field() }}
                         <div class="row">
                              <div class="col-md-12">
                                   @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                        <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                                   @endif
                              </div>
                         </div>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" placeholder="Nombre" name="name" class="form-control" value="{{ old('name') }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Apellidos</label>
                                        <input type="text" name="surnames" placeholder="Apellidos" class="form-control" value="{{ old('surnames') }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Correo</label>
                                        <input type="email"  value="{{ old('email') }}" name="email" placeholder="Correo" class="form-control">
                                   </div>
                              </div>
                         </div>
                         <hr>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Contraseña</label>
                                        <input type="password" name="password" placeholder="Contraseña" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Confirmar Contraseña</label>
                                        <input type="password" name="password_confirmation" placeholder="Confirmar contraseña" class="form-control">
                                   </div>
                              </div>
                         </div>
                         <hr>

                         <a  href="{{ url('admin/admin') }}" class="btn btn-fill btn-wd btn-default">
                              <i class="fa fa-arrow-left" aria-hidden="true"></i>
                              Regresar
                         </a>
                         <button type="submit" class="btn btn-fill btn-success btn-wd pull-right">
                              <i class="fa fa-floppy-o" aria-hidden="true"></i>
                              Registrar administrador
                         </button>
                    </form>
               </div>
          </div>
     </div>
</div>
@stop

resources/views/admin/admin/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <h4 class="card-title">
                         Editar participante
                    </h4>
               </div>
               <div class="card-content ">
                    <form class="form" method="post" action="{{ route('admin.admin.update', $admin) }}">
                         {{ csrf_field() }} {{ method_field('PUT') }}
                         <div class="row">
                              <div class="col-md-12">
                                   @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                        <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                                   @endif
                              </div>
                         </div>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" placeholder="Nombre" name="name" class="form-control"  value="{{ $admin->name }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Apellidos</label>
                                        <input type="text" name="surnames" placeholder="Apellidos" class="form-control" value="{{ $admin->surnames }}">
                                   </div>
                              </div>

                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Correo</label>
                                        <input type="email"  value="{{  $admin->email }}" name="email" placeholder="Correo" class="form-control">
                                   </div>
                              </div>

                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Estatus</label><br>
                                        <input
                                             name="status"
                                             @if($admin->status == 1) checked @endif
                                             type="checkbox"
                                             value="1"
                                             data-toggle="toggle"
                                             data-width="150"
                                             data-on="Activo"
                                             data-off="Inactivo"
                                             data-onstyle="success"
                                             data-offstyle="danger"
                                        >
                                   </div>
                              </div>
                         </div>
                         <hr>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Contraseña</label>
                                        <input type="password" name="password" placeholder="Contraseña" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Confirmar Contraseña</label>
                                        <input type="password" name="password_confirmation" placeholder="Confirmar contraseña" class="form-control">
                                   </div>
                              </div>
                         </div>
                         <hr>

                         <a  href="{{ url('admin/admin') }}" class="btn btn-fill btn-wd btn-default">
                              <i class="fa fa-arrow-left" aria-hidden="true"></i>
                              Regresar
                         </a>
                         <button type="submit" class="btn btn-fill btn-success btn-wd pull-right">
                              <i class="fa fa-floppy-o" aria-hidden="true"></i>
                              Editar administrador
                         </button>
                    </form>
               </div>
          </div>
     </div>
</div>
@stop
@push('scripts')
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
@endpush

@push('style')
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">

<style>
span.badge.badge-secondary{
     width: 100%;
    padding: 10px;
    background-color: #f3f2ee;
    color: #6a615b;
    border-radius: 5px;
    border: 1px solid #ddd;
}

</style>
@endpush

resources/views/admin/admin/index.blade.php
@extends('admin.layout')

@section('content')

<div class="row">
     <div class="col-xs-6">
          <a href="{{ url('/admin') }}">
               <h4 style="margin-top:3px;"><span class="label label-success">
                    <i class="fa fa-arrow-left"></i> Atras</span></h4>
          </a>
     </div>
     <div class="col-xs-6" style="text-align: right;">
          <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Inicio</a></li>
               <li class="breadcrumb-item active" aria-current="page">Lista de administradores</li>
          </ol>
     </div>
</div>

<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <a href="{{ route('admin.admin.create') }}" class="btn btn-wd btn-success" style="float:right; z-index:9999;">
                         <span class="btn-label">
                              <i class="fa fa-plus"></i>
                         </span>
                         Agregar un nuevo administrador
                    </a>
                    <h4 class="card-title">Lista de administradores</h4>
                    <p class="category">Administradores registrados</p>

               </div>
               <div class="card-content table-responsive table-full-width">
                    <table class="table">
                         <thead>
                              <tr>
                                   <th class="text-center">#</th>
                                   <th>Nombre</th>
                                   <th class="text-center">Estatus</th>
                                   <th class="text-center">Actions</th>
                              </tr>
                         </thead>
                         <tbody>
                              @forelse($admins as $key => $admin)
                              <tr>
                                   <td class="text-center">{{ $admin->id }}</td>
                                   <td>{{ $admin->name }} {{ $admin->surnames }}</td>
                                   <td class="text-center">
                                        @if($admin->status == 1)
                                             <span class="label label-success">Activo</span>
                                        @else
                                             <span class="label label-danger">Inactivo</span>
                                        @endif
                                   </td>
                                   <td class="td-actions text-center">
                                        <a href="{{ route('admin.admin.edit', $admin) }}" rel="tooltip" title="" class="btn btn-success  btn-simple btn-xs" data-original-title="Editar">
                                             <i class="ti-pencil-alt"></i>
                                        </a>
                                        <form method="POST"
                                             action="{{ route('admin.admin.destroy', $admin) }}"
                                             style="display:inline">
                                             {{ csrf_field() }} {{ method_field('DELETE') }}
                                             <button class="btn btn-xs btn-simple btn-danger"
                                                  onclick="return confirm('¿ Estás seguro de querer eliminar este administrador ?')"
                                              >
                                              <i class="fa fa-trash"></i>
                                             </button>
                                        </form>
                              </td>
                         </tr>
                         @empty
                         <tr>
                              <td colspan="5" class="text-center">Sin registros</td>
                         </tr>
                         @endforelse
                    </tbody>
               </table>
          </div>
     </div>
</div>
</div>
@stop