routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/



// Página principal
Route::get('/', 'PageController@home')->name('visitor.dashboard.index');

// Autenticación Visitor
Route::auth();

// Obtener municipios
     Route::get('municipios', 'PageController@municipios')->name('municipios');

// Grupo Visitor
Route::group([
     'prefix' => 'visitor',
     'namespace' => 'Visitor',
     'middleware' => 'auth'],
     function(){
          Route::get('/', 'DashboardController@index')->name('visitor.dashboard');
          Route::get('/resource_group/{group_id}', 'ResourceController@index')->name('visitor.resource_group');
          Route::get('/see_resource/{resource_id}', 'ResourceController@see_resource')->name('visitor.see_resource');

          Route::get('my_account', 'UserController@my_account')->name('visitor.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('visitor.my_account_update');
});

// Login Admin
Route::get('/admin/login', 'Auth\LoginAdminController@showLoginForm')->name('admin.login');
Route::post('/admin/login', 'Auth\LoginAdminController@login');


// Grupo Admin
Route::group([
     'prefix' => 'admin',
     'namespace' => 'Admin',
     'middleware' => 'is_admin'],
      function(){
          Route::get('/', 'DashboardController@index')->name('dashboard');
          Route::resource('visitor', 'UserController', ['as' => 'admin']);
          Route::resource('group', 'ResourceGroupController', ['as' => 'admin']);
          Route::resource('admin', 'AdminController', ['as' => 'admin']);

          Route::post('activate_resource', 'ResourceController@activate_resource')->name('admin.activate_resource');

          Route::get('my_account', 'UserController@my_account')->name('admin.my_account');
          Route::put('my_account_update', 'UserController@my_account_update')->name('admin.my_account_update');


          Route::group(['prefix' => '{group_id}'], function($group_id){
               Route::resource('resource', 'ResourceController');
          });

          Route::post('order_group', 'ResourceGroupController@order_group')->name('admin.order_group');

          Route::post('order_resource', 'ResourceController@order_resource')->name('admin.order_resource');

});

// Salir de sesión
Route::get('logout', 'Auth\LoginController@logout')->name('logout');

resources/views/admin/resources/create.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <h4 class="card-title">
                         {{ $group->name }} \ Alta de tema
                    </h4>
               </div>
               <div class="card-content ">
                    <form method="post" enctype="multipart/form-data" action="{{ url('admin/'.$group->id.'/resource' ) }}">
                         {{ csrf_field() }}
                         <div class="row">
                              <div class="col-md-12">
                                   @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                        <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                                   @endif
                              </div>
                         </div>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" placeholder="Nombre" name="nombre" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Tipo de recurso</label>
                                        <select class="form-control" name="resource_type_id" id="resource_type_id" onchange="cambio_archivo()">
                                             @foreach ($resourcetype as $key => $type)
                                             <option value="{{ $type->id }}"> {{ $type->name }}</option>
                                             @endforeach
                                        </select>
                                   </div>
                              </div>
                              <div class="col-md-12" id="div_archivo">
                                   <label for="name">Archivo</label>
                                   <div class="input-group">
                                        <label class="input-group-btn">
                                             <span class="btn btn-info">
                                                  Archivo &hellip; <input type="file" name="input_file" id="input_file" style="display: none;">
                                             </span>
                                        </label>
                                        <input type="text" id="text_file" class="form-control" readonly>
                                   </div>
                              </div>

                              <div class="col-md-12" id="div_link" style="display:none;">
                                   <div class="form-group">
                                        <label>Link del recurso</label>
                                        <input type="url" placeholder="link" id="url" name="url" class="form-control">
                                   </div>
                              </div>

                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Autor del recurso</label>
                                        <input type="text" placeholder="Autor" name="author" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Especialidad del autor</label>
                                        <input type="text" placeholder="Especialidad" name="author_specialty" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>Descripción</label><br>
                                        <textarea class="form-control" rows="8" cols="80" name="description"></textarea>
                                   </div>
                              </div>
                         </div>
                         <hr>

                         <a  href="{{ url('admin/'.$group->id.'/resource') }}" class="btn btn-fill btn-wd btn-default">
                              <i class="fa fa-arrow-left" aria-hidden="true"></i>
                              Regresar
                         </a>
                         <button type="submit" class="btn btn-fill btn-success btn-wd pull-right">
                              <i class="fa fa-floppy-o" aria-hidden="true"></i>
                              Publicar recurso
                         </button>
                    </form>
               </div>
          </div>
     </div>
</div>
@stop
@push('style')
<style>

video { display:block; width:100%; border:none; border: 1px solid #eee; border-radius: 5px; background-color: #ddd};
embed{ display:block; width:100%; border:none; border: 1px solid #eee;  border-radius: 5px; background-color: #ddd };

.bord{
     border: 1px solid #e8e7e3 !important;
     border-radius: 5px;
     padding: 10px;
}

.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}


</style>
@endpush


@push('scripts')
<script>
$(function() {

  // We can attach the `fileselect` event to all file inputs on the page
  $(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  // We can watch for our custom `fileselect` event like this
  $(document).ready( function() {
     cambio_archivo();

      $(':file').on('fileselect', function(event, numFiles, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
  });

});


function cambio_archivo() {
     $('#div_archivo').hide();
     $('#div_link').hide();
     $('#text_file').val('');
     $('#input_file').val('');
     $('#url').val('');

     var resource_type_id =  $('#resource_type_id').val();
     switch (resource_type_id) {
          case '1':
               $('#div_archivo').show();
               $('#input_file').attr("accept", "application/pdf");
          break;
          case '2':
               $('#div_archivo').show();
               $('#input_file').attr("accept", "image/*");
          break;
          case '3':
               $('#div_archivo').show();
               $('#input_file').attr("accept", "video/mp4");
          break;
          case '4':
               $('#div_link').show();
          break;


     }
}

</script>

@endpush

resources/views/admin/resources/edit.blade.php
@extends('admin.layout')

@section('content')
<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <h4 class="card-title">
                         {{ $group->name }} \ Editar tema
                    </h4>
               </div>
               <div class="card-content ">
                    <form method="post" enctype="multipart/form-data" action="{{ route('resource.update', ['group_id' => $group->id, 'resource' =>  $resource ] ) }}">
                         {{ csrf_field() }} {{ method_field('PUT') }}

                         <div class="row">
                              <div class="col-md-12">
                                   @if($errors->any())
                                   <ul class="list-group">
                                        @foreach($errors->all() as $key => $error)
                                        <li class="list-group-item list-group-item-danger"> {{ $error }}</li>
                                        @endforeach
                                   </ul>
                                   @endif
                              </div>
                         </div>
                         <div class="row">
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Nombre</label>
                                        <input type="text" placeholder="Nombre" name="nombre" class="form-control" value="{{ $resource->name }}">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Tipo de recurso</label>
                                        <select class="form-control" name="resource_type_id" id="resource_type_id" onchange="cambio_archivo()">
                                             @foreach ($resourcetype as $key => $type)
                                             <option
                                                  @if( $resource->resource_type_id == $type->id ) selected @endif
                                                  value="{{ $type->id }}"
                                             >
                                             {{ $type->name }}
                                             </option>
                                             @endforeach
                                        </select>
                                   </div>
                              </div>
                              <div class="col-md-12" id="div_archivo">
                                   <label for="name">Archivo</label>
                                   <div class="input-group">
                                        <label class="input-group-btn">
                                             <span class="btn btn-info">
                                                  Archivo &hellip; <input type="file" name="input_file" id="input_file" style="display: none;">
                                             </span>
                                        </label>
                                        <input type="text" class="form-control" readonly>
                                   </div>
                                   <hr>
                                   <label>Archivo actual</label>
                                   <div class="row">
                                        <div class="col-md-12">
                                             <div class="col-md-12  text-center"  style="height:300px; border-radiborder-radius: 5px; borde:1px solid #eee; background-color:#ddd; overflow-y:auto;">
                                        <?php if ( $resource->file): ?>
                                             <?php if($resource->resource_type_id == '1'): ?>
                                                <iframe src="{{ $resource->file }}" width="100%" height="500px" style="margin: 0 auto;"></iframe>
                                             <?php elseif($resource->resource_type_id == '2'): ?>
                                                  <img src="{{ $resource->file }}" alt="" style="margin-top: 15%; margin: 0 auto;">
                                             <?php elseif($resource->resource_type_id == '3'): ?>
                                                  <video src="{{ $resource->file }}" controls style="width:500px; margin: 0 auto;" >
                                                  </video>
                                             <?php endif; ?>
                                        <?php endif; ?>

                                             </div>
                                        </div>
                                   </div>
                                   <hr>
                              </div>

                              <div class="col-md-12" id="div_link">
                                   <div class="form-group">
                                        <label>Link del recurso</label>
                                        <input type="text" placeholder="link" name="url" value="{{ $resource->url }}" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Autor del recurso</label>
                                        <input type="text" placeholder="Autor" value="{{ $resource->author }}" name="author" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-6">
                                   <div class="form-group">
                                        <label>Especialidad del autor</label>
                                        <input type="text" placeholder="Especialidad" value="{{ $resource->author_specialty }}" name="author_specialty" class="form-control">
                                   </div>
                              </div>
                              <div class="col-md-12">
                                   <div class="form-group">
                                        <label>Descripción</label><br>
                                        <textarea name="description" class="form-control" rows="8" cols="80" name="description"> {{ $resource->description }}</textarea>
                                   </div>
                              </div>
                         </div>
                         <hr>

                         <a  href="{{ url('admin/'.$group->id.'/resource') }}" class="btn btn-fill btn-wd btn-default">
                              <i class="fa fa-arrow-left" aria-hidden="true"></i>
                              Regresar
                         </a>
                         <button type="submit" class="btn btn-fill btn-success btn-wd pull-right">
                              <i class="fa fa-floppy-o" aria-hidden="true"></i>
                              Publicar recurso
                         </button>
                    </form>
               </div>
          </div>
     </div>
</div>
@stop
@push('style')
<style>

video { display:block; width:100%; border:none; border: 1px solid #eee; border-radius: 5px; background-color: #ddd};
embed{ display:block; width:100%; border:none; border: 1px solid #eee;  border-radius: 5px; background-color: #ddd };

.bord{
     border: 1px solid #e8e7e3 !important;
     border-radius: 5px;
     padding: 10px;
}

.btn-file {
    position: relative;
    overflow: hidden;
}
.btn-file input[type=file] {
    position: absolute;
    top: 0;
    right: 0;
    min-width: 100%;
    min-height: 100%;
    font-size: 100px;
    text-align: right;
    filter: alpha(opacity=0);
    opacity: 0;
    outline: none;
    background: white;
    cursor: inherit;
    display: block;
}


</style>
@endpush


@push('scripts')
<script>
$(function() {

  // We can attach the `fileselect` event to all file inputs on the page
  $(document).on('change', ':file', function() {
    var input = $(this),
        numFiles = input.get(0).files ? input.get(0).files.length : 1,
        label = input.val().replace(/\\/g, '/').replace(/.*\//, '');
    input.trigger('fileselect', [numFiles, label]);
  });

  // We can watch for our custom `fileselect` event like this
  $(document).ready( function() {
     cambio_archivo();

      $(':file').on('fileselect', function(event, numFiles, label) {

          var input = $(this).parents('.input-group').find(':text'),
              log = numFiles > 1 ? numFiles + ' files selected' : label;

          if( input.length ) {
              input.val(log);
          } else {
              if( log ) alert(log);
          }

      });
  });

});


function cambio_archivo() {
     $('#div_archivo').hide();
     $('#div_link').hide();
     $('#text_file').val('');
     $('#input_file').val('');
     $('#url').val('');

     var resource_type_id =  $('#resource_type_id').val();
     switch (resource_type_id) {
          case '1':
               $('#div_archivo').show();
               $('#input_file').attr("accept", "application/pdf");
          break;
          case '2':
               $('#div_archivo').show();
               $('#input_file').attr("accept", "image/*");
          break;
          case '3':
               $('#div_archivo').show();
               $('#input_file').attr("accept", "video/mp4");
          break;
          case '4':
               $('#div_link').show();
          break;


     }
}

</script>

@endpush

resources/views/admin/resources/index.blade.php
@extends('admin.layout')

@section('content')

<div class="row">
     <div class="col-xs-6">
          <a href="{{ url('/admin') }}">
               <h4 style="margin-top:3px;"><span class="label label-success">
                    <i class="fa fa-arrow-left"></i> Atras</span></h4>
          </a>
     </div>
     <div class="col-xs-6" style="text-align: right;">
          <ol class="breadcrumb">
               <li class="breadcrumb-item"><a href="{{ url('/admin') }}">Inicio</a></li>
               <li class="breadcrumb-item active" aria-current="page">Lista de temas -> {{ $group->name }}</li>
          </ol>
     </div>
</div>

<div class="row">
     <div class="col-md-12">
          <div class="card">
               <div class="card-header">
                    <a href="{{ url('admin/'.$group->id.'/resource/create') }}" class="btn btn-wd btn-success" style="float:right; z-index:9999;">
                         <span class="btn-label">
                              <i class="fa fa-plus"></i>
                         </span>
                         Agregar un nuevo tema
                    </a>
                    <h4 class="card-title">Temario</h4>
                    <p class="category"> {{ $group->name }} \ Temas disponibles</p>
               </div>
               <div class="card-content table-responsive table-full-width">
                    <table class="table">
                         <thead>
                              <tr>
                                   <th class="text-center">#</th>
                                   <th class="text-center">Tema</th>
                                   <th class="text-center">Tipo de recurso</th>
                                   <th class="text-center">Fecha de publicación</th>
                                   <th class="text-center">Activo</th>
                                   <th class="text-center">Actions</th>
                              </tr>
                         </thead>
                         <tbody id="example1">
                              @forelse ($resource as $resource)
                              <tr id="{{ $resource->id }}">
                                   <td class="text-center">{{ $resource->id }}</td>
                                   <td class="text-center">{{ $resource->name }}</td>
                                   <td class="text-center">{{ $resource->resource_type->name }}</td>
                                   @if($resource->publication_date)
                                        <td class="text-center"> {{ \Carbon\Carbon::parse($resource->publication_date)->diffForHumans() }}</td>
                                   @else
                                        <td class="text-center">Sin fecha</td>
                                   @endif
                                   <td class="text-center">
                                        <input
                                             class="status_resource"
                                             type="checkbox"
                                             data-resource="{{ $resource->id }}"
                                             data-toggle="toggle"
                                             data-size="sm"
                                             @if( $resource->status == 1) checked @endif
                                        >

                                   </td>
                                   <td class="td-actions text-center">
                                        <a href="{{  route('resource.edit',  ['group_id' => $group->id, 'resource' => $resource ] ) }}" rel="tooltip" title="" class="btn btn-success btn-simple btn-xs" data-original-title="Editar">
                                             <i class="ti-pencil-alt"></i>
                                        </a>

                                        <form method="POST"
                                             action="{{ route('resource.destroy', [ 'group_id' => $group->id, 'resource' => $resource ]) }}"
                                             style="display:inline">
                                             {{ csrf_field() }} {{ method_field('DELETE') }}
                                             <button class="btn btn-xs btn-simple btn-danger"
                                                  onclick="return confirm('¿ Estás seguro de querer eliminar este recurso ?')"
                                             >
                                             <i class="fa fa-trash"></i>
                                             </button>
                                        </form>
                                   </td>
                              </tr>

                              @empty
                              <tr>
                                   <td colspan="5">Sin recursos</td>
                              </tr>
                              @endforelse


                         </tbody>
                    </table>
               </div>
          </div>
     </div>
</div>
@stop
@push('scripts')
<script src="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/js/bootstrap4-toggle.min.js"></script>
<script src="{!! asset('js/Sortable.js') !!}" charset="utf-8"></script>
<script src="{!! asset('js/st/prettify/prettify.js') !!}" charset="utf-8"></script>
<script src="{!! asset('js/st/prettify/run_prettify.js') !!}" charset="utf-8"></script>
<script>
     $.ajaxSetup({
          headers: {
               'X-CSRF-TOKEN': $('meta[name="csrf-token"]').attr('content')
          }
     });

     var example1 = document.getElementById('example1');
     new Sortable(example1, {
     	animation: 150,
     	ghostClass: 'blue-background-class',
          onUpdate: function(evt) {
          console.log(evt);
          var order= $("#example1 tr").map(function() {
               return this.id;
          }).get();
            f='order='+order;
            $.ajax({
                 type: "POST",
                 data : f,
                 cache: false,
                 url: " {{ route('admin.order_resource')}}",
                 success: function(data){
                    //success
                 }
            });
	    },
     });

</script>

<script>
$('.status_resource').change(function() {
     var status = $(this).prop('checked');
     var resource_id = $(this).data("resource");
     var _token = $("input[name='_token']").val();

     $.ajax({
          data: {  _token:_token, status : status, resource_id: resource_id },
          url: "{{ route('admin.activate_resource') }}",
          type: "POST",
          dataType: 'json',
          beforeSend : function( xhr ) {
          	$('.status_resource').bootstrapToggle('disable')
          },
          success: function (data) {
               var men = data.status == 1 ? 'Activado' : 'Desactivado' ;
               Swal.fire(
                 'Exito',
                  'Se '+men+' correctamente',
                 'success'
               )
          },
          error: function (data) {
               console.log('Error:', data);
               $('#btn-save').html('Save Changes');
          },
          complete: function() {
               $('.status_resource').bootstrapToggle('enable');
          }

     });

})
</script>
@endpush

@push('style')
<link href="https://cdn.jsdelivr.net/gh/gitbrent/bootstrap4-toggle@3.6.1/css/bootstrap4-toggle.min.css" rel="stylesheet">
@endpush